### ISSUE TITLE
Not all GeoJSON parsers support single quotes

### ISSUE THREAD

**Issue by markdeaton** [atlefren/locationhistory2geojson#1]
GeoJSONLint.com won't recognize the output.

Recommend modifying the code to do this:
import json
...
print json.dumps(feature)

**Comment by atlefren** [comment]
Ok, to clarify:

By GeoJSON I meant GeoJSON in the same way Shapely defines "Python Geo Interface" (https://gist.github.com/sgillies/2217756)

There is a difference between a (Geo)Json string and the sctructure that is dumped to that string, but I may tend to mix those two.

My thought was that the extra step of stringifying and then parsing python objects for working further with them is an unnessecarry performance hit, and for my needs not needed. I should probably have mentioned that in order to produce actual GeoJSON you have to use json.dumps, but as far as this "libray" goes that's all I'm going to do about it

**Comment by atlefren** [comment]
And, this has nothing to do with me using single quotes for my Python data, when you use json.dumps valid json is produced, before you use json.dumps it's not json

**Comment by markdeaton** [comment]
That is completely fair. Thank you for this code; it saved me a lot of time over writing it myself. The small modification of using dumps lets me import my Google location history into arcgis.
